### ISSUE TITLE
Isn't all of this stolen content from books and you didnt contribute anything on your own?

### ISSUE THREAD

**Issue by badgateway666** [hexterisk/hexterisk.github.io#1]
Hey, you forgot to mention that your whole blog is a ripoff from this book https://practicalbinaryanalysis.com/ by Dennis Andriesse .
I thought that would be fair to mention since you didn't even contribute your own examples but literally just copied all your content and put "Copyright by <you>" on it.

**Comment by hexterisk** [comment]
It is majorly from PBA, however includes things that I couldn't find and
looked around for. Credits should have been added though, I'm at a fault
there. Will do the needful with the next push.
Thank you.

**Comment by badgateway666** [comment]
Thanks for handling this =)
